spring.application.name=Gestion-immobilier

spring.datasource.url=jdbc:postgresql://localhost:5432/gestionimmobilier
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.hikari.schema=gestionimmobilier

spring.jpa.hibernate.ddl-auto=update
# Logging
spring.jpa.show-sql=false
server.port=8081


secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
expiration: 86400000 
expirationR: 604800000

# Chemin de stockage des images (en dehors du projet)
image.storage.path=C:\Users\pc\Desktop\img
storage.location=uploads
# Désactive la validation automatique du Content-Type
spring.servlet.multipart.resolve-lazily=true

# Augmente les limites de taille
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Force le traitement multipart
spring.servlet.multipart.enabled=true